# action.yml
name: 'Mypy Check'
description: 'GitHub action to run mypy on your repository'
branding:
  icon: 'check-square'
  color: 'blue'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: false
    default: '${{ github.token }}'
  path:
    description: 'File or directory to run mypy on'
    required: false
    default: '.'
  mypy_args:
    description: 'Command line argument for mypy'
    required: false
    default: '--show-column-numbers --hide-error-context'
outputs:
  output:
    description: 'The output of mypy'
runs:
  using: 'docker'
  image: 'Dockerfile'
